### ISSUE TITLE
copy attempts to interpret URI containing "[" as regex

### ISSUE THREAD

**Issue by dkloving** [fsspec/s3fs#565]
When an URI includes the "[" character, `S3FileSystem.copy` attempts to interpret as a regex causing copy to fail to locate the file even though `S3FileSystem.exists` does locate the file and returns True.

I suppose this may be desired default behavior to match expectations from other file systems (?) but it would be good to have a way to prevent it.

**Comment by martindurant** [comment]
You are right, this is expected, because "[" is a special character for glob. You can work around it by using copy_file instead, but of course that only works for one file. If you want to do recursive, you would need to use find and copy_file on the results (ideally with asyncio.gather), something like the current copy without attempting the glob. If you *do* also want glob, I think you are out of luck.

**Comment by dkloving** [comment]
Thanks, but it seems like `copy_file` is not a function of `S3FileSystem` and I can't find any reference to it in the API doc. How do I access this function?

**Comment by martindurant** [comment]
Sorry, `cp_file` (and its coroutine counterpart `_cp_file`).

**Comment by dkloving** [comment]
Awesome that solved it, thanks!
