### ISSUE TITLE
any alternative to aiohttp?

### ISSUE THREAD

**Issue by tooptoop4** [fsspec/s3fs#638]
it brings in 2 CVEs and aiohttp has not had a release in few years

![image](https://user-images.githubusercontent.com/33283496/185057257-65ef4895-3d21-4116-86f3-101fed08e0ea.png)

https://github.com/aio-libs/aiohttp/discussions/6827

**Comment by efiop** [comment]
@tooptoop4 There are no good alternatives. Though aiohttp has been released less than a year ago (pretty normal for stable project), so it is really not bad. It is also indeed not clear how the CVE you've linked is related to aiohttp at all. Maybe it is a false-positive in your CVE scanner (not sure what you use) and you could dismiss it.

Closing for now since there is not much we can do with this in s3fs.
