### ISSUE TITLE
Async Open and read contents of the file. 

### ISSUE THREAD

**Issue by vminfant** [fsspec/s3fs#706]
I'm trying to open and read the contents of the file from s3 with an async function but the below code snippet is hanging forever.  could anyone please highlight issues surrounding this? 

```python
async def open_file():
    fs = s3fs.S3FileSystem(anon=False, loop=asyncio.get_running_loop())
    session = await fs.set_session()
    f = await fs._open("s3://fileopentestbucket/logs.txt", mode="rb")
    data = await f.read(-1)
    f.close()
    await session.close()


asyncio.run(open_file())
```

_Environment details:_ 

Python version: `3.10.7`
s3fs version: `2023.1.0`
Operating System: MacOS
Install method (conda, pip, source): poetry

**Comment by martindurant** [comment]
Unfortunately, the python file-like API is not compatible with async. 

There is an attempt to make some async-freindly version of the API, with fsspec.asyn.AbstractAsyncStreamedFile, but this is only currently used by fsspec.implementations.http.AsyncStreamFile , which you get via fs.open_async . It is not implemented for gcs or s3. The trouble is, files maintain a state: the current file location and buffer. It becomes very hard to reason about when file operations potentially happen out of order due to concurrency.

**Comment by vminfant** [comment]
hi @martindurant .. Sure! thanks for your feedback.
