### ISSUE TITLE
Usage with PyScript

### ISSUE THREAD

**Issue by quasiben** [fsspec/s3fs#728]
I was playing around with Pandas and S3 Parquet data and attempted to write a PyScript example to build a dashboard .  I was blocked by s3fs not having a Python 3 wheel.  This seems odd as pypi lists a pure python 3 wheel here:
https://pypi.org/project/s3fs/#files

error:
> (PY1001): Unable to install package(s) 's3fs'. Reason: Can't find a pure Python 3 Wheel for package(s) 's3fs'. See: https://pyodide.org/en/stable/usage/faq.html#micropip-can-t-find-a-pure-python-wheel for more information.

```html
<html>
<head>
<link rel="stylesheet" href="https://pyscript.net/latest/pyscript.css" />
<script defer src="https://pyscript.net/latest/pyscript.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>
<body>
<py-config type="toml">
    packages = ["s3fs"]
</py-config>

<py-script>
# Import libraries
import s3fs
</py-script>
</body>
</html>
```

**Comment by quasiben** [comment]
Ah right!  Forgot about the asyncio issue.  Thanks for the thoughtful response!

**Comment by martindurant** [comment]
Sidelong related: dask-distributed has a websocket protocol, which is what it would need for communication from pyscript. That could also solve the S3 issue, since we can then proxy client calls via workers. I'm pretty sure, though, that the thread and tornado stuff even in the client side is too much for pyscript. I'd be happy to brainstorm on what it might take to get this to work.
